name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      version: ${{ steps.changelog.outputs.version }}
      skip: ${{ steps.changelog.outputs.skipped }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-git-pull: true

  publish-tauri:
    needs: changelog
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    if: ${{ needs.changelog.outputs.skip != 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          ref: ${{ needs.changelog.outputs.tag }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: setup homebrew
        if: matrix.platform == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: cleanup / upgrade homebrew
        if: matrix.platform == 'macos-latest'
        run: |
          brew cleanup
          brew upgrade

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: use Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          cache-on-failure: true

      - name: install opencv (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install opencv --params "/InstallationPath:C:\"

      - name: install opencv (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install opencv@4
        env: 
          HOMEBREW_NO_AUTO_UPDATE: true

      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OpenCV_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\opencv\\build' }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ needs.changelog.outputs.tag}} # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'MuskelAnalyse ${{ needs.changelog.outputs.version }}'
          releaseBody: ${{ needs.changelog.outputs.changelog }}
          releaseDraft: false
          prerelease: false
